version: "3.1"

services:
  jenkins:
    build:
     context: .
    image: jenkins:1.0
    ports:
     - "8080:8080"
    volumes:
     - $HOME/data/jenkins:/var/jenkins_home 

  tomcat:
    image: tomcat
    ports:
      - "8087:8080"
    links:
      - postgres
    volumes:
     - $HOME/data/tomcat:/usr/local/tomcat/webapps
    restart: always

#  sonar:
#    image: sonarqube
#   ports:
#     - "9000:9000"
#    volumes:
#     - /$HOME/data/sonar:/var/jenkins_home
#   restart: always
  nexus:
    image: sonatype/nexus3
    ports:
      - "80:8081"
      - "8082:8082"
      - "8083:8083"
    links:
      - tomcat
    volumes:
     - $HOME/data/nexus-data:/nexus-data
    restart: always
  postgres:
    image: postgres
    volumes:
       - $HOME/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_DB=deml
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    networks:
      - postgres
    restart: always

  pgadmin:
    links:
     - postgres
    image: fenglc/pgadmin4
    volumes:
      - $HOME/data/pgadmin:/var/lib
    ports:
     - "5050:5050"
    networks:
     - postgres
    restart: always

networks:
  postgres:
    driver: bridge
    
