version: "3.1"

services:
  jenkins:
    build:
      context: .
    image: saurabhpathak21/myjenkins:1.2
    ports:
     - "8086:8080"
    depends_on:
#     - sonar
     - nexus
#    links:
#      - tomcat
    volumes:
     - /$HOME/data/jenkins:/var/jenkins_home
    restart: always
    
  tomcat:
    image: tomcat
    ports:
      - "8080:8080"
    links:
      - postgres
    volumes:
     - /$HOME/data/tomcat:/usr/local/tomcat/webapps
    restart: always

#  sonar:
#    image: sonarqube
#    ports:
#     - "9000:9000"
#    volumes:
#     - /$HOME/data/sonar:/var/jenkins_home
#   restart: always
  nexus:
    image: sonatype/nexus3
    ports:
      - "80:8081"
      - "8082:8082"
      - "8083:8083"
    links:
      - tomcat
    volumes:
     - /$HOME/data/nexus-data:/nexus-data
    restart: always
  postgres:
    image: postgres
    volumes:
       - /$HOME/data/postgres:/data/postgres
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_DB=deml
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    networks:
      - postgres
    restart: always

  pgadmin:
    links:
     - postgres
    image: fenglc/pgadmin4
    volumes:
      - /$HOME/data/pgadmin:/root/.pgadmin
    ports:
     - "5050:5050"
    networks:
     - postgres
    restart: always

networks:
  postgres:
    driver: bridge
